# Uncomment the next line to define a global platform for your project
# platform :ios, '6.0'

target 'tetris2048-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tetris2048-desktop

end

target 'tetris2048-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tetris2048-mobile

pod 'Google-Mobile-Ads-SDK'
end
