var g_resources = [
   "res/sound/button.wav",
   "res/sound/dead.wav",
   "res/sound/down.wav",
   "res/sound/merge1.wav",
   "res/sound/merge2.wav",
   "res/sound/merge3.wav",
   "res/atlas.png",
   "res/atlas.plist",
   "res/p-1.png",
   "res/p-2.png",
   "res/p-3.png",
];

var res = {
   sbutton: "res/sound/button.wav",
   sdead: "res/sound/dead.wav",
   sdown: "res/sound/down.wav",
   smerge1: "res/sound/merge1.wav",
   smerge2: "res/sound/merge2.wav",
   smerge3: "res/sound/merge3.wav",
   atlas: "res/atlas.png",
   atlasPlist: "res/atlas.plist",
   p1: "res/p-1.png",
   p2: "res/p-2.png",
   p3: "res/p-3.png",

   back1: "#back-1.png",
   back2: "#back-2.png",
   next: "#next.png",
   p1list1: "#p-1-list1.png",
   p1list2: "#p-1-list2.png",
   p1play1: "#p-1-play-1.png",
   p1play2: "#p-1-play-2.png",
   p1shop1: "#p-1-shop1.png",
   p1shop2: "#p-1-shop2.png",
   p1shopW1: "#p-1-shopW1.png",
   p1shopW2: "#p-1-shopW2.png",
   p1shopW3E: "#p-1-shopW3-E.png",
   p1shopW3: "#p-1-shopW3.png",
   p1shopW4E: "#p-1-shopW4-E.png",
   p1shopW4: "#p-1-shopW4.png",
   p1shopW5E: "#p-1-shopW5-E.png",
   p1shopW5: "#p-1-shopW5.png",
   p1shopW6E: "#p-1-shopW6-E.png",
   p1shopW6: "#p-1-shopW6.png",
   p1shopW7: "#p-1-shopW7.png",
   p1sound1: "#p-1-sound1.png",
   p1sound2: "#p-1-sound2.png",
   p3home1: "#p-3-home1.png",
   p3home2: "#p-3-home2.png",
   p3retry1: "#p-3-retry1.png",
   p3retry2: "#p-3-retry2.png",
   p3share1: "#p-3-share1.png",
   p3share2: "#p-3-share2.png",
   p3stop: "#p-3-stop.png",
   p41E: "#p-4-1-E.png",
   p41: "#p-4-1.png",
   p42: "#p-4-2.png",
   p43E: "#p-4-3-E.png",
   p43: "#p-4-3.png",
   p44E: "#p-4-4-E.png",
   p44: "#p-4-4.png",
   p45E: "#p-4-5-E.png",
   p45: "#p-4-5.png",
   relax1: "#RELAX1.png",
   relax2: "#RELAX2.png",
   stop1: "#stop-1.png",
   stop2: "#stop-2.png",
};
