var res = {
   sbutton: "res/sound/button.wav",
   sdead: "res/sound/dead.wav",
   sdown: "res/sound/down.wav",
   smerge1: "res/sound/merge1.wav",
   smerge2: "res/sound/merge2.wav",
   smerge3: "res/sound/merge3.wav",

   back1: "res/back-1.png",
   back2: "res/back-2.png",
   next: "res/next.png",
   p1list1: "res/p-1-list1.png",
   p1list2: "res/p-1-list2.png",
   p1play1: "res/p-1-play-1.png",
   p1play2: "res/p-1-play-2.png",
   p1shop1: "res/p-1-shop1.png",
   p1shop2: "res/p-1-shop2.png",
   p1shopW1: "res/p-1-shopW1.png",
   p1shopW2: "res/p-1-shopW2.png",
   p1shopW3E: "res/p-1-shopW3-E.png",
   p1shopW3: "res/p-1-shopW3.png",
   p1shopW4E: "res/p-1-shopW4-E.png",
   p1shopW4: "res/p-1-shopW4.png",
   p1shopW5E: "res/p-1-shopW5-E.png",
   p1shopW5: "res/p-1-shopW5.png",
   p1shopW6E: "res/p-1-shopW6-E.png",
   p1shopW6: "res/p-1-shopW6.png",
   p1shopW7: "res/p-1-shopW7.png",
   p1sound1: "res/p-1-sound1.png",
   p1sound2: "res/p-1-sound2.png",
   p1: "res/p-1.png",
   p2: "res/p-2.png",
   p3home1: "res/p-3-home1.png",
   p3home2: "res/p-3-home2.png",
   p3retry1: "res/p-3-retry1.png",
   p3retry2: "res/p-3-retry2.png",
   p3share1: "res/p-3-share1.png",
   p3share2: "res/p-3-share2.png",
   p3stop: "res/p-3-stop.png",
   p3: "res/p-3.png",
   p41E: "res/p-4-1-E.png",
   p41: "res/p-4-1.png",
   p42: "res/p-4-2.png",
   p43E: "res/p-4-3-E.png",
   p43: "res/p-4-3.png",
   p44E: "res/p-4-4-E.png",
   p44: "res/p-4-4.png",
   p45E: "res/p-4-5-E.png",
   p45: "res/p-4-5.png",
   relax1: "res/RELAX1.png",
   relax2: "res/RELAX2.png",
   stop1: "res/stop-1.png",
   stop2: "res/stop-2.png",
};

var g_resources = [];
for (var i in res) {
   g_resources.push(res[i]);
}
